/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crazy_xdien_imageedit_sliding_MainActivity */

JNIEXPORT jstring JNICALL com_crazy_xdien_imageedit_sliding_process_jniMatEffects_getStringFromNative
  (JNIEnv *env,  jobject obj)
  {
        return (*env) -> NewStringUTF(env,"asdasdkjhjhkkjj");
}